"""initial_storage_schema

Revision ID: 77bff60de574
Revises:
Create Date: 2026-09-06 01:58:05.532823+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77bff60de574"  # pragma: allowlist secret
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema modifications."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("source_url", sa.String(length=512), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("priority_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
    )
    with op.batch_alter_table("data_sources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_data_sources_source_code"),
            ["source_code"],
            unique=True,
        )

    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("city", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("division", sa.String(length=32), nullable=False),
        sa.Column("conference", sa.String(length=64), nullable=False),
        sa.Column("logo_url", sa.String(length=512), nullable=True),
        sa.Column("website", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
    )
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_teams_name"), ["name"], unique=True)

    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.String(length=128), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("venue", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("result", sa.String(length=16), nullable=True),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.Column("season", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
            name=op.f("fk_games_away_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
            name=op.f("fk_games_home_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_games")),
    )
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_games_away_team_id"),
            ["away_team_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_games_game_id"), ["game_id"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_games_home_team_id"),
            ["home_team_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_games_season"), ["season"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_games_start_time"),
            ["start_time"],
            unique=False,
        )

    op.create_table(
        "raw_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_raw_snapshots_source_id_data_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_snapshots")),
    )
    with op.batch_alter_table("raw_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_raw_snapshots_captured_at"),
            ["captured_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_raw_snapshots_content_hash"),
            ["content_hash"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_raw_snapshots_source_id"),
            ["source_id"],
            unique=False,
        )

    op.create_table(
        "sync_audits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("sync_cycle_id", sa.String(length=64), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("games_created", sa.Integer(), nullable=False),
        sa.Column("games_updated", sa.Integer(), nullable=False),
        sa.Column("games_deleted", sa.Integer(), nullable=False),
        sa.Column("conflicts_detected", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_sync_audits_source_id_data_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_audits")),
    )
    with op.batch_alter_table("sync_audits", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sync_audits_source_id"),
            ["source_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_sync_audits_started_at"),
            ["started_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_sync_audits_sync_cycle_id"),
            ["sync_cycle_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema modifications."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sync_audits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_audits_sync_cycle_id"))
        batch_op.drop_index(batch_op.f("ix_sync_audits_started_at"))
        batch_op.drop_index(batch_op.f("ix_sync_audits_source_id"))

    op.drop_table("sync_audits")
    with op.batch_alter_table("raw_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_snapshots_source_id"))
        batch_op.drop_index(batch_op.f("ix_raw_snapshots_content_hash"))
        batch_op.drop_index(batch_op.f("ix_raw_snapshots_captured_at"))

    op.drop_table("raw_snapshots")
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_games_start_time"))
        batch_op.drop_index(batch_op.f("ix_games_season"))
        batch_op.drop_index(batch_op.f("ix_games_home_team_id"))
        batch_op.drop_index(batch_op.f("ix_games_game_id"))
        batch_op.drop_index(batch_op.f("ix_games_away_team_id"))

    op.drop_table("games")
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_teams_name"))

    op.drop_table("teams")
    with op.batch_alter_table("data_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_data_sources_source_code"))

    op.drop_table("data_sources")
    # ### end Alembic commands ###
