"""Schedule reconciliation and conflict resolution package."""

from __future__ import annotations

from ecu_hockey_calendar.reconciliation.change_detector import (
    CANONICAL_CHANGE_CYCLE_PREFIX,
    ChangeDetector,
)
from ecu_hockey_calendar.reconciliation.date_aligner import (
    DEFAULT_EXACT_TOLERANCE_MINUTES,
    DEFAULT_NEAR_TOLERANCE_MINUTES,
    DEFAULT_TIMEZONE,
    DateTimeAlignmentResult,
    align_game_datetimes,
    compute_date_distance_days,
    compute_time_difference_minutes,
    is_start_time_tbd,
    to_local_date,
    to_local_datetime,
)
from ecu_hockey_calendar.reconciliation.engine import (
    CANONICAL_ECU_NAME,
    CANONICAL_SEASON,
    ReconciliationEngine,
)
from ecu_hockey_calendar.reconciliation.fuzzy_matcher import (
    GENERIC_COLLEGE_TERMS,
    KNOWN_MASCOTS,
    VENUE_ALIASES,
    compute_opponent_similarity,
    compute_venue_similarity,
    is_opponent_match,
    is_venue_match,
    is_venue_unspecified,
    strip_mascot_terms,
)
from ecu_hockey_calendar.reconciliation.models import (
    DEFAULT_SOURCE_TIE_BREAKERS,
    DEFAULT_SOURCE_TIERS,
    ChangeDetectionCycleResult,
    ConflictField,
    ConflictSeverity,
    DetectedConflict,
    DiscrepancyRecord,
    FieldDiff,
    GameChangeRecord,
    GameStateTransition,
    ReconciledGame,
    ReconciliationCycleResult,
    ReconciliationStatus,
    SourceGameRecord,
    SourcePriority,
    TimingRelationship,
)

__all__ = [
    "CANONICAL_CHANGE_CYCLE_PREFIX",
    "CANONICAL_ECU_NAME",
    "CANONICAL_SEASON",
    "DEFAULT_EXACT_TOLERANCE_MINUTES",
    "DEFAULT_NEAR_TOLERANCE_MINUTES",
    "DEFAULT_SOURCE_TIERS",
    "DEFAULT_SOURCE_TIE_BREAKERS",
    "DEFAULT_TIMEZONE",
    "GENERIC_COLLEGE_TERMS",
    "KNOWN_MASCOTS",
    "VENUE_ALIASES",
    "ChangeDetectionCycleResult",
    "ChangeDetector",
    "ConflictField",
    "ConflictSeverity",
    "DateTimeAlignmentResult",
    "DetectedConflict",
    "DiscrepancyRecord",
    "FieldDiff",
    "GameChangeRecord",
    "GameStateTransition",
    "ReconciledGame",
    "ReconciliationCycleResult",
    "ReconciliationEngine",
    "ReconciliationStatus",
    "SourceGameRecord",
    "SourcePriority",
    "TimingRelationship",
    "align_game_datetimes",
    "compute_date_distance_days",
    "compute_opponent_similarity",
    "compute_time_difference_minutes",
    "compute_venue_similarity",
    "is_opponent_match",
    "is_start_time_tbd",
    "is_venue_match",
    "is_venue_unspecified",
    "strip_mascot_terms",
    "to_local_date",
    "to_local_datetime",
]
