"""Ingestion pipeline for multi-source crawler, HTML parsing, and normalization."""

from __future__ import annotations

from ecu_hockey_calendar.ingestion.acchockey_crawler import (
    DEFAULT_ACCHL_SCHEDULE_URL,
    DEFAULT_PAGINATION_LIMIT,
    ACCHockeyCrawler,
)
from ecu_hockey_calendar.ingestion.acchockey_parser import (
    DEFAULT_ACCHL_SEASON,
    DEFAULT_BASE_URL,
    extract_pagination_urls,
    extract_schedule_urls,
    extract_season_from_html,
    extract_subseason_urls,
    parse_acchockey_game_html,
    parse_acchockey_schedule_html,
)
from ecu_hockey_calendar.ingestion.client import (
    DEFAULT_BACKOFF_FACTOR,
    DEFAULT_MAX_RETRIES,
    DEFAULT_TIMEOUT,
    DEFAULT_USER_AGENT,
    RETRYABLE_STATUS_CODES,
    ResilientHttpClient,
    compute_content_hash,
)
from ecu_hockey_calendar.ingestion.ecuhockey_crawler import (
    DEFAULT_FIRESTORE_URL,
    DEFAULT_RESULTS_HTML_URL,
    DEFAULT_TEAM_ID,
    DEFAULT_UPCOMING_HTML_URL,
    ECUHockeyCrawler,
    parse_firestore_game_document,
)
from ecu_hockey_calendar.ingestion.html_parser import (
    DEFAULT_ECU_TEAM,
    ParsedGameRecord,
    parse_schedule_html,
)
from ecu_hockey_calendar.ingestion.instagram_crawler import (
    DEFAULT_CACHE_TTL_SECONDS,
    DEFAULT_RATE_LIMIT_INTERVAL,
    CacheEntry,
    InstagramCrawler,
    RateLimiter,
    SessionCache,
)
from ecu_hockey_calendar.ingestion.instagram_parser import (
    DEFAULT_GRAPH_API_URL,
    DEFAULT_INSTAGRAM_URL,
    DEFAULT_INSTAGRAM_USERNAME,
    DEFAULT_WEB_PROFILE_URL,
    IG_APP_ID,
    AnnouncementType,
    ParsedInstagramPost,
    classify_announcement,
    cross_reference_announcements_with_games,
    extract_date_from_caption,
    extract_opponent_from_caption,
    extract_time_from_caption,
    extract_venue_from_caption,
    parse_graph_api_response,
    parse_html_instagram_feed,
    parse_public_feed_json,
    resolve_game_status_from_announcement,
)
from ecu_hockey_calendar.ingestion.normalizer import (
    DEFAULT_TIMEZONE,
    normalize_team_name,
    parse_game_datetime,
    parse_game_score,
    parse_game_status,
)
from ecu_hockey_calendar.ingestion.tickets_crawler import (
    DEFAULT_TICKETS_PAGE_URL,
    TicketsCrawler,
)
from ecu_hockey_calendar.ingestion.tickets_parser import (
    ParsedTicketRecord,
    TicketPriceTier,
    cross_reference_tickets_with_games,
    extract_opponent_from_title,
    extract_promotional_theme,
    identify_ticketing_vendor,
    parse_firestore_ticket_doc,
    parse_firestore_tickets_response,
    parse_html_ticket_listings,
    parse_price_text,
)

__all__ = [
    "DEFAULT_ACCHL_SCHEDULE_URL",
    "DEFAULT_ACCHL_SEASON",
    "DEFAULT_BACKOFF_FACTOR",
    "DEFAULT_BASE_URL",
    "DEFAULT_CACHE_TTL_SECONDS",
    "DEFAULT_ECU_TEAM",
    "DEFAULT_FIRESTORE_URL",
    "DEFAULT_GRAPH_API_URL",
    "DEFAULT_INSTAGRAM_URL",
    "DEFAULT_INSTAGRAM_USERNAME",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_PAGINATION_LIMIT",
    "DEFAULT_RATE_LIMIT_INTERVAL",
    "DEFAULT_RESULTS_HTML_URL",
    "DEFAULT_TEAM_ID",
    "DEFAULT_TICKETS_PAGE_URL",
    "DEFAULT_TIMEOUT",
    "DEFAULT_TIMEZONE",
    "DEFAULT_UPCOMING_HTML_URL",
    "DEFAULT_USER_AGENT",
    "DEFAULT_WEB_PROFILE_URL",
    "IG_APP_ID",
    "RETRYABLE_STATUS_CODES",
    "ACCHockeyCrawler",
    "AnnouncementType",
    "CacheEntry",
    "ECUHockeyCrawler",
    "InstagramCrawler",
    "ParsedGameRecord",
    "ParsedInstagramPost",
    "ParsedTicketRecord",
    "RateLimiter",
    "ResilientHttpClient",
    "SessionCache",
    "TicketPriceTier",
    "TicketsCrawler",
    "classify_announcement",
    "compute_content_hash",
    "cross_reference_announcements_with_games",
    "cross_reference_tickets_with_games",
    "extract_date_from_caption",
    "extract_opponent_from_caption",
    "extract_opponent_from_title",
    "extract_pagination_urls",
    "extract_promotional_theme",
    "extract_schedule_urls",
    "extract_season_from_html",
    "extract_subseason_urls",
    "extract_time_from_caption",
    "extract_venue_from_caption",
    "identify_ticketing_vendor",
    "normalize_team_name",
    "parse_acchockey_game_html",
    "parse_acchockey_schedule_html",
    "parse_firestore_game_document",
    "parse_firestore_ticket_doc",
    "parse_firestore_tickets_response",
    "parse_game_datetime",
    "parse_game_score",
    "parse_game_status",
    "parse_graph_api_response",
    "parse_html_instagram_feed",
    "parse_html_ticket_listings",
    "parse_price_text",
    "parse_public_feed_json",
    "parse_schedule_html",
    "resolve_game_status_from_announcement",
]
